[project]
name = "automenu_api"
version = "0.1.0"
description = "The backend for the SpoonFed meal planning app."
readme = "../README.md"
authors = [{ name = "Krzysiek Setlak", email = "bigfoot19@wp.pl" }]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.136.3",
    "pyjwt>=2.13.0",
    "sqlalchemy[asyncio]>=2.0.50",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=9.1.1",
    "ruff>=0.15.17",
]

## Build
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["automenu_api"]

## Ruff
[tool.ruff]
# Docs: https://docs.astral.sh/ruff/configuration/
line-length = 120
exclude = [".venv/"]

[tool.ruff.lint]
# You probably want to add more rules here. See docs.
# https://docs.astral.sh/ruff/rules/
select = [
    "B",   # bugs (https://pypi.org/project/flake8-bugbear/)
    "E",   # pycodestyle errors (https://pypi.org/project/pycodestyle/)
    "W",   # pycodestyle warnings
    "F",   # pyflakes (https://pypi.org/project/pyflakes/)
    "I",   # isort (https://pypi.org/project/isort/)
    "C90", # complexity (https://pypi.org/project/mccabe/)
    "S",   # security (https://pypi.org/project/flake8-bandit/)
]

[tool.ruff.lint.per-file-ignores]
# Allow asserts in tests
"tests/**/*.py" = ["S101"]

[tool.fastapi]
entrypoint = "main:app"
